import importlib.util
import pathlib
import unittest


SCRIPT_PATH = pathlib.Path(__file__).parent.parent / "scripts" / "parse_md.py"
SPEC = importlib.util.spec_from_file_location("parse_md", SCRIPT_PATH)
parse_md = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(parse_md)


class ParseMdSplitTests(unittest.TestCase):
    def test_no_headings_single_section(self):
        sections = parse_md.split_sections("Just some text\nand more text")
        self.assertEqual(len(sections), 1)
        self.assertEqual(sections[0][0], "")
        self.assertIn("Just some text", sections[0][1])

    def test_h1_splits_into_sections(self):
        md = "# Section A\nContent A\n# Section B\nContent B"
        sections = parse_md.split_sections(md)
        self.assertEqual(len(sections), 2)
        self.assertEqual(sections[0][0], "Section A")
        self.assertEqual(sections[1][0], "Section B")

    def test_h2_also_splits(self):
        md = "## Alpha\nfoo\n## Beta\nbar"
        sections = parse_md.split_sections(md)
        self.assertEqual(len(sections), 2)
        self.assertEqual(sections[0][0], "Alpha")

    def test_h3_splits_too(self):
        md = "# Top\n### Sub\ncontent"
        sections = parse_md.split_sections(md)
        self.assertEqual(len(sections), 2)
        self.assertEqual(sections[0][0], "Top")
        self.assertEqual(sections[1][0], "Sub")

    def test_heading_line_included_in_block_text(self):
        md = "# Intro\nparagraph"
        sections = parse_md.split_sections(md)
        # block_text starts with the raw "# Intro" line
        self.assertTrue(sections[0][1].startswith("# Intro"))


class ParseMdImageTests(unittest.TestCase):
    def test_image_replaced_with_placeholder(self):
        body = "![Logo](https://example.com/logo.png)"
        text, refs = parse_md.process_text_refs(body, 1)
        self.assertNotIn("![", text)
        self.assertIn("[Image:md-image-1-1 Logo]", text)
        self.assertEqual(len(refs), 1)
        self.assertEqual(refs[0]["ref_type"], "image")
        self.assertEqual(refs[0]["url"], "https://example.com/logo.png")

    def test_image_without_alt_uses_empty_placeholder(self):
        body = "![](img.png)"
        text, refs = parse_md.process_text_refs(body, 2)
        self.assertIn("[Image:md-image-2-1]", text)
        self.assertEqual(refs[0]["label"], "img.png")

    def test_image_processed_before_link(self):
        body = "![alt](url.png) and [link](https://x.com)"
        text, refs = parse_md.process_text_refs(body, 1)
        image_refs = [r for r in refs if r["ref_type"] == "image"]
        link_refs = [r for r in refs if r["ref_type"] == "link"]
        self.assertEqual(len(image_refs), 1)
        self.assertEqual(len(link_refs), 1)
        # image syntax is no longer in text
        self.assertNotIn("![", text)


class ParseMdLinkTests(unittest.TestCase):
    def test_link_url_stripped_from_body(self):
        body = "See [docs](https://docs.example.com) for details"
        text, refs = parse_md.process_text_refs(body, 1)
        self.assertNotIn("https://docs.example.com", text)
        self.assertIn("docs", text)
        self.assertEqual(refs[0]["url"], "https://docs.example.com")
        self.assertEqual(refs[0]["anchor_text"], "docs")

    def test_multiple_links_sequential_ids(self):
        body = "[A](https://a.com) and [B](https://b.com)"
        text, refs = parse_md.process_text_refs(body, 3)
        self.assertEqual(refs[0]["ref_id"], "md-link-3-1")
        self.assertEqual(refs[1]["ref_id"], "md-link-3-2")

    def test_anchor_link_not_external(self):
        body = "[top](#top)"
        text, refs = parse_md.process_text_refs(body, 1)
        self.assertFalse(refs[0]["is_external"])

    def test_image_not_captured_as_link(self):
        body = "![alt](img.png) and [link](https://x.com)"
        text, refs = parse_md.process_text_refs(body, 1)
        link_refs = [r for r in refs if r["ref_type"] == "link"]
        self.assertEqual(len(link_refs), 1)
        self.assertEqual(link_refs[0]["url"], "https://x.com")


class ParseMdGfmTableTests(unittest.TestCase):
    def test_gfm_table_kept_as_is_in_text(self):
        """GFM tables are NOT extracted or re-rendered; they stay in the body text."""
        body = "| A | B |\n| - | - |\n| 1 | 2 |"
        text, refs = parse_md.process_text_refs(body, 1)
        # table syntax preserved verbatim
        self.assertIn("| A | B |", text)
        # no table refs generated by parse_md
        table_refs = [r for r in refs if r["ref_type"] == "table"]
        self.assertEqual(table_refs, [])

    def test_link_inside_table_stripped(self):
        body = "| [doc](https://x.com) | B |\n| - | - |\n| 1 | 2 |"
        text, refs = parse_md.process_text_refs(body, 1)
        self.assertNotIn("https://x.com", text)
        self.assertIn("doc", text)


class ParseMdPageCountTests(unittest.TestCase):
    def test_page_count_is_always_one(self):
        import json, io, sys
        from pathlib import Path
        import tempfile

        md_content = "# A\ntext\n# B\nmore"
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            f.write(md_content)
            tmp = f.name

        old_argv = sys.argv
        old_stdout = sys.stdout
        try:
            sys.argv = ["parse_md.py", tmp]
            buf = io.StringIO()
            sys.stdout = buf
            result = parse_md.main()
            sys.stdout = old_stdout
            self.assertEqual(result, 0)
            payload = json.loads(buf.getvalue())
            self.assertEqual(payload["page_count"], 1)
            self.assertEqual(len(payload["pages"]), 2)
        finally:
            sys.argv = old_argv
            sys.stdout = old_stdout
            Path(tmp).unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()
