networks:
  net: { name: local, driver: bridge, external: true }

services:
  rag:
    image: q.local/rag:latest
    restart: always
    container_name: rag
    networks: ["net"]
    ports: [127.0.0.1:3060:3060]
    user: 1000:1000
    volumes:
    - ./configs:/app/configs
    #- ./configs/app.json:/app/target/spa/ui/app.json
    - ./data/documents:/app/data/documents
    - ./data/static:/app/data/static
    - ./logs:/app/logs
    environment:
      TZ: Asia/Shanghai
    command: ["target/server", "--release", "--config=configs/local.yaml", "--addr=:3060"]
