ARG node_tag=24-alpine
ARG golang_tag=1-alpine
ARG python_tag=3.14-alpine

#### Stage 1
FROM node:${node_tag} AS frontend-build

ARG build_region
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG git_branch=unknown
ARG git_commit=unknown
ARG commit_time=unknown

ENV http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy"

WORKDIR /app

ADD frontend/index.html frontend/*.json frontend/*.js  ./
COPY frontend/public  ./public
COPY frontend/src  ./src

RUN if [ "$build_region" == "cn" ]; then \
        npm config set registry https://registry.npmmirror.com; \
    fi

ENV BASE_PATH=/ui \
    GIT_BRANCH="$git_branch" \
    GIT_COMMIT="$git_commit" \
    COMMIT_TIME="$commit_time"

RUN npm install
RUN npm run build

#### Stage 2
FROM golang:${golang_tag} AS backend-build

ARG build_region
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG git_branch=unknown
ARG git_commit=unknown
ARG commit_time=unknown
ARG version_pkg=github.com/d2jvkpn/rag/backend/pkg/infra

ENV http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy"

WORKDIR /app
ADD backend/go.mod backend/go.sum ./
COPY backend/main.go ./
COPY backend/internal ./internal
COPY backend/pkg ./pkg

RUN if [ "$build_region" == "cn" ]; then \
        go env -w GOPROXY=https://goproxy.cn,direct; \
    fi

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags \
      "-s -w -X '${version_pkg}.GitBranch=${git_branch}' -X '${version_pkg}.GitCommit=${git_commit}' -X '${version_pkg}.CommitTime=${commit_time}'" \
      -o target/server .

#### Stage 3
FROM python:${python_tag} AS runtime

ARG build_region
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy"

ARG PUID=1000
ARG PGID=1000

RUN if [ "$build_region" = "cn" ]; then \
        echo "==> build_region: $build_region"; \
        mv /etc/apk/repositories /etc/apk/repositories.bk; \
        cp /etc/apk/repositories.bk /etc/apk/repositories; \
        sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    fi

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add tzdata coreutils ca-certificates

WORKDIR /app

RUN addgroup -g "$PGID" appuser && \
    adduser -D -H -u "$PUID" -G appuser -h /app -s /sbin/nologin appuser && \
    mkdir -p /app/configs /app/data /app/logs /app/target && \
    chown -R appuser:appuser /app

COPY --from=backend-build /app/target /app/target
COPY --from=frontend-build /app/target/dist /app/target/spa/ui
#RUN sed -i 's/:3061/:3060/' /app/target/spa/ui/app.json

COPY backend/examples/local.yaml /app/configs/local.yaml
COPY backend/scripts /app/scripts

ENV PDF_PARSER_SCRIPT=/app/scripts/parse_pdf.py

USER appuser:appuser

RUN if [ "$build_region" == "cn" ]; then \
        pip3 config set global.index-url 'https://pypi.tuna.tsinghua.edu.cn/simple'; \
        pip3 config set install.trusted-host 'pypi.tuna.tsinghua.edu.cn'; \
    fi

RUN pip3 install --upgrade pip && \
    pip3 install -r scripts/parse_pdf.pip.txt

ENV FRONTEND_CONFIG=/app/target/spa/ui/app.json

EXPOSE 3060
ENV http_proxy="" https_proxy="" no_proxy=""

VOLUME /app/configs
VOLUME /app/data
VOLUME /app/logs

ENTRYPOINT []
CMD ["target/server", "--release", "--config=configs/local.yaml", "--addr=:3060"]
