####
FROM node:24-alpine AS frontend-build

WORKDIR /app

ADD frontend/*.json frontend/*.js frontend/index.html  ./
COPY frontend/public  ./public
COPY frontend/src  ./src

RUN npm config set registry https://registry.npmmirror.com

ENV BASE_PATH=/ui \
    OUT_DIR=target/dist

RUN npm install &> /dev/null && \
    npm run build

####
FROM golang:1-alpine AS backend-build

WORKDIR /app
ADD backend/go.mod backend/go.sum ./
COPY backend/cmd ./cmd
COPY backend/internal ./internal

RUN go env -w GOPROXY=https://goproxy.cn,direct

RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o target/main ./cmd/server

####
FROM alpine:3 AS runtime

WORKDIR /app

RUN addgroup -g 1000 appuser \
    && adduser -D -H -u 1000 -G appuser -h /app -s /sbin/nologin appuser \
    && mkdir -p /app/configs /app/data /app/logs /app/target

COPY --from=frontend-build /app/target/dist /app/target/ui
RUN sed -i 's/:3061/:3060/' /app/target/ui/app.json

COPY --from=backend-build /app/target/main /app/target
COPY backend/examples/local.yaml /app/configs/local.yaml

RUN chown -R 1000:1000 /app

USER 1000:1000
EXPOSE 3060

ENV FRONEND_CONFIG=/app/target/ui/app.json

VOLUME /app/configs
VOLUME /app/data
VOLUME /app/logs

ENTRYPOINT []
CMD ["target/main", "--release", "--config=configs/local.yaml", "--addr=:3060"]
